### PR TITLE
feat: add Nuxt module prefix (#59)

### PR DESCRIPTION
**Pull request by shinGangan**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The following three changes were made in this PR.

1. add Nuxt module prefix (`@nuxtjs`)
2. fix nuxt core groups
3. rename 'config:base' to 'config:recommended

#### 1. add Nuxt module prefix (`@nuxtjs`)

I am using `renovate-config-nuxt` as extends in my product development.
In many cases, Nuxt Modules are not included and must be added separately. For example, `@nuxtjs/tailwindcss`, `@nuxtjs/i18n`, `@nuxtjs/apollo`, etc.

Considering that many more Nuxt Modules will be added in the future, we thought it would be nice to include Nuxt Module in the `nuxt framework` group.

#### 2. fix nuxt core groups

If you use the `matchPackageNames` options, many packages that will be added in the future may not be included.
For example, `@nuxt/content`, `@nuxt/ui`, and `@nuxt/image` are currently not included.

Therefore, we are refactoring the options to use `matchPackagePrefixes`.

#### 3. rename 'config:base' to 'config:recommended

`config:base` is renamed to `config:recommended`.

- ref: [renovatebot/renovate#21136](https://github.com/renovatebot/renovate/pull/21136)

### Content not addressed in this PR

- add `@nuxthq`.
  - We decided it would be better to include it in a separate PR

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### 🙏 Note

Hi @danielroe (and dear nuxt team).

Thank you for developing Nuxt. We are thrilled to be able to develop our product with the addition of new and wonderful features every day.

This PR is not a high priority because it is not a feature addition that will affect Nuxt users.
Also, we are modifying it in a way that will not affect many users of renovate-config-nuxt (we could have added modules.json, but we decided not to this time).

We would appreciate your review when you have a time. Thank you in advance. 🙏
(Local testing has already been successful).

### CODE REVIEW

**Comment by danielroe** [comment]
I am not sure we should add `@nuxtjs/` to the Nuxt _framework_ ruleset. We also have an allow-list. The idea is that it only includes core Nuxt updates (and packages are specified by name to avoid other core repo updates like image or content: see https://github.com/nuxt/renovate-config-nuxt/pull/45#discussion_r946473636). But you could implement this in your own renovate preset.

If you want to update the PR to be just the name change for base -> recommended then we could go ahead with that change.

**Comment by shinGangan** [comment]
@danielroe , thank you for your comment and instruction.
I also checked #45 and now I know why I did not include `@nuxt`.

I am thinking of issuing a separate PR again for the following since PR content is different.
Or is it preferable to modify this PR?

> If you want to update the PR to be just the name change for base -> recommended then we could go ahead with that change.

**Comment by danielroe** [comment]
A separate PR would also be perfect 👌

**Comment by shinGangan** [comment]
Understood.
I would like to close this PR and submit another PR. Thank you very much.

**Pull request closed without merging**
